[package]
name = "blockchain"
version = "0.1.3"
description = "Generic Blockchain interface"
license = "Apache-2.0"
repository = "https://github.com/sorpaas/blockchain-rs"
authors = ["Wei Tang <hi@that.world>"]

[dependencies]
